/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import BLL.GameBLL;
import Model.MealModel;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author re_hs
 */
public class PresentationPage extends javax.swing.JFrame {

    private final GameBLL game;
    private int answer;
    /**
     * Creates new form PresentationPage
     */
    public PresentationPage() {
        this.game = GameBLL.getInstance();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setText("Pense em um prato, vou advinha-lo.");
        jLabel1.setName("lblTitle"); // NOI18N

        jButton1.setText("OK");
        jButton1.setToolTipText("");
        jButton1.setName("btnOk"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        
        gameStart();
        
        this.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PresentationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new PresentationPage().setVisible(true);
        });
    }
    
    private void gameStart() {
        answer = JOptionPane.showConfirmDialog(rootPane, 
                                               "O prato que você pensou é massa?", 
                                               "Confirmar", 
                                               JOptionPane.YES_NO_OPTION);

        if (answer == JOptionPane.YES_OPTION) {
            guessMeal(game.pastas);
            return;
        }

        guessMeal(game.notPastas);        
    }
    
    private void guessMeal(ArrayList<MealModel> meals) {
        int counter;
        int sizeList = meals.size() - 1;

        for (counter = sizeList; counter > 0; counter--) {
            answer = askMeal(meals, counter, true);
            if (answer == JOptionPane.YES_OPTION) {
                answer = askMeal(meals, counter, false);
                if (answer == JOptionPane.YES_OPTION) {
                    iWon();
                    break;                    
                } else if ((answer == JOptionPane.NO_OPTION) && 
                           (counter == 0)) {
                    addMeal(meals);
                    break;                    
                }
            }
        }
        
        if (counter == 0) {
            answer = askMeal(meals, counter, false);
            if (answer == JOptionPane.YES_OPTION) {
                iWon();
                return;                
            }
            addMeal(meals);            
        }
    }
        
    private int askMeal(ArrayList<MealModel> meals, 
                        int counter, 
                        boolean optDescription) {
        
        StringBuilder meal = new StringBuilder();
        if (optDescription) {
            meal.append("O prato que pensou é ")
                .append(meals.get(counter).getDescription())
                .append(" ?");
            return JOptionPane.showConfirmDialog(rootPane, 
                                                 meal.toString(), 
                                                 "Confirmar", 
                                                 JOptionPane.YES_NO_OPTION);
        }
        
        meal.append("O prato que pensou é ")
            .append(meals.get(counter).getName())
            .append(" ?");
        
            return JOptionPane.showConfirmDialog(rootPane, 
                                                 meal.toString(), 
                                                 "Confirmar", 
                                                 JOptionPane.YES_NO_OPTION);
    }
    
   
    private void addMeal(ArrayList<MealModel> meals) {     
        String nameMeal = JOptionPane.showInputDialog(rootPane, 
                                                      "Qual prato você pensou?", 
                                                      "Desisto", 
                                                      JOptionPane.QUESTION_MESSAGE);
       
        if (nameMeal != null && !nameMeal.isEmpty()) {
            StringBuilder description = new StringBuilder();
            description.append("Descreva uma caracteristica de ")
                       .append(nameMeal);
        
            String descriptionMeal = JOptionPane.showInputDialog(rootPane, 
                                                                 description.toString(), 
                                                                 "Completo", 
                                                                 JOptionPane.QUESTION_MESSAGE);
        
            meals.add(new MealModel(nameMeal, descriptionMeal));
        }
    }
    
    private void iWon() {
        JOptionPane.showMessageDialog(rootPane, 
                                      "Acertei de novo!", 
                                      "Jogo Gourmet", 
                                      JOptionPane.INFORMATION_MESSAGE);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}

